import { Category } from "./types";

// Part 3: Recommended MVP Category Tree (v1) — hardcoded per spec.
// Every Tier-2 category maps to exactly one schema.org type and carries a
// requires_license_verification flag.
export const categories: Category[] = [
  {
    slug: "food-drink",
    name: "Food & Drink",
    schemaType: "FoodEstablishment",
    requiresLicenseVerification: false,
    subcategories: [
      "Restaurants",
      "Bakeries & Pastry",
      "Grocery & Markets",
      "Butchers & Meat",
      "Cafés & Dessert",
      "Catering",
      "Hookah Lounges",
      "Sweets & Confectionery",
    ],
  },
  {
    slug: "health-medical",
    name: "Health & Medical",
    schemaType: "MedicalBusiness",
    requiresLicenseVerification: true,
    subcategories: [
      "Primary Care",
      "Dentists",
      "OB-GYN",
      "Pediatrics",
      "Pharmacy",
      "Optometry",
      "Mental Health & Counseling",
      "Physical Therapy",
      "Dermatology",
      "Cardiology",
    ],
  },
  {
    slug: "legal",
    name: "Legal",
    schemaType: "LegalService",
    requiresLicenseVerification: true,
    subcategories: [
      "Immigration",
      "Family",
      "Criminal Defense",
      "Personal Injury",
      "Business & Corporate",
      "Estate Planning",
      "Real Estate Law",
    ],
  },
  {
    slug: "financial-insurance",
    name: "Financial & Insurance",
    schemaType: "FinancialService",
    requiresLicenseVerification: true,
    subcategories: [
      "Accountants / CPA & Tax",
      "Bookkeeping",
      "Insurance Agents (Auto/Home/Life/Health)",
      "Financial Advisors",
      "Notary",
    ],
  },
  {
    slug: "real-estate",
    name: "Real Estate",
    schemaType: "RealEstateAgent",
    requiresLicenseVerification: true,
    subcategories: ["Agents & Brokers", "Property Management", "Mortgage / Loan Officers", "Commercial"],
  },
  {
    slug: "home-services",
    name: "Home Services",
    schemaType: "HomeAndConstructionBusiness",
    requiresLicenseVerification: true,
    licenseNote: "Contractors",
    subcategories: [
      "General Contractors",
      "Plumbing",
      "Electrical",
      "HVAC",
      "Roofing",
      "Landscaping",
      "Cleaning",
      "Handyman",
      "Moving",
      "Pest Control",
    ],
  },
  {
    slug: "auto-services",
    name: "Auto Services",
    schemaType: "AutomotiveBusiness",
    requiresLicenseVerification: true,
    licenseNote: "Smog / Repair facilities",
    subcategories: ["Repair", "Body Shops", "Smog & Inspection", "Tires", "Dealers", "Detailing"],
  },
  {
    slug: "beauty-personal-care",
    name: "Beauty & Personal Care",
    schemaType: "HealthAndBeautyBusiness",
    requiresLicenseVerification: false,
    licenseNote: "Except cosmetology licenses",
    subcategories: ["Barbers", "Hair Salons", "Skin & Esthetics", "Nails", "Bridal / Henna"],
  },
  {
    slug: "faith-community",
    name: "Faith & Community",
    schemaType: "CivicStructure",
    requiresLicenseVerification: true,
    licenseNote: "IRS nonprofit EIN check",
    subcategories: [
      "Mosques",
      "Churches (Coptic Orthodox, Chaldean/Assyrian Catholic, Maronite, Melkite, Greek Orthodox)",
      "Community Centers",
      "Nonprofits & Social Services",
      "Cemeteries & Funeral Services",
    ],
  },
  {
    slug: "education-childcare",
    name: "Education & Childcare",
    schemaType: "ChildCare",
    requiresLicenseVerification: true,
    licenseNote: "Daycares / schools",
    subcategories: ["Arabic Language Schools", "Islamic & Christian Day Schools", "Tutoring", "Preschool / Childcare", "Quran / Religious Instruction"],
  },
  {
    slug: "shops-events-services",
    name: "Shops, Events & Services",
    schemaType: "ProfessionalService",
    requiresLicenseVerification: false,
    subcategories: [
      "Clothing & Modest Wear",
      "Jewelry",
      "Gifts & Home",
      "Bookstores & Media",
      "Travel Agencies",
      "Event Venues",
      "Photographers",
      "DJs & Entertainment",
      "Printing",
      "Translation & Interpreting",
      "Wireless / Electronics",
    ],
  },
];

export function getCategory(slug: string): Category | undefined {
  return categories.find((c) => c.slug === slug);
}
