import { Listing } from "./types";

// Phase 0 seed data.
//
// Per Rule 3 (Zero Local Scraping of Google or Yelp) this file contains NO data
// copied or cached from Google Maps or Yelp. Per Rule 1 (the Self-Identification
// Rule), Arab ownership is never inferred — it is only set from an authenticated
// owner claim ("self_identified") or a cited public statement made by the
// business itself ("documented_public_claim"). Every other field below is drawn
// from the two organizations' own public pages, as documented in the Southern
// California research pack.
//
// A first real Part 6, Stage 1 ingestion pass has now been run for Orange
// County: place-of-worship POIs pulled live from OpenStreetMap via the public
// Overpass API (ODbL-licensed, public domain reuse — not Google/Yelp), with
// city assigned either from OSM's own addr:city tag or, where that was
// missing, from a Nominatim (also OSM-based) reverse geocode of the node's
// coordinates. Every mosque/church record below carries only what OSM itself
// states: its name, religious affiliation, and location — never an ownership
// claim. Category/city pages that still sit under the 3-listing indexing
// threshold (Part 8) remain noindexed until further ingestion or owner claims
// populate them; see noindex.ts.
export const listings: Listing[] = [
  {
    listingId: "aabc-irvine",
    name: "Arab American Business Chamber (AABC)",
    slug: "arab-american-business-chamber",
    primaryCategory: "faith-community",
    secondaryCategories: ["shops-events-services"],
    address: {
      street: "2801 Main Street, Suite 413",
      locality: "Irvine",
      region: "CA",
      postal: "92614",
    },
    hasPublicStorefront: true,
    countySlug: "orange-county",
    citySlug: "irvine",
    telephone: "(949) 287-2465",

    arabOwnedSelfIdentified: "documented_public_claim",
    arabOwnedSource: "Organization's own published mission statement",
    arabOwnedAttestedBy: "AABC public website (fetched via research, Sept 2026)",

    claimStatus: "unclaimed",
    verificationLevel: "contact_verified",
    provenance: {
      source: "Public organization website",
      method: "Manual editorial entry from cited public source",
      recordedAt: "2026-09-01",
    },
    closureStatus: "open",
    isSponsored: false,
    professionalDisclaimerShown: false,
    editorialNote:
      "A regional chamber of commerce serving Arab American professionals, entrepreneurs, and small business owners. States its purpose as \"advancing economic opportunity, strategic partnerships, and sustainable business growth within the Arab American community.\" Board includes President & CEO Farah Kanchar.",
  },
  {
    listingId: "american-arab-chamber-anaheim",
    name: "American Arab Chamber of Commerce — Anaheim",
    slug: "american-arab-chamber-of-commerce-anaheim",
    primaryCategory: "faith-community",
    secondaryCategories: ["shops-events-services"],
    hasPublicStorefront: false,
    serviceArea: ["Anaheim, CA", "Orange County, CA"],
    countySlug: "orange-county",
    citySlug: "anaheim",

    arabOwnedSelfIdentified: "documented_public_claim",
    arabOwnedSource: "Organization's own published mission statement",
    arabOwnedAttestedBy: "American Arab Chamber of Commerce public website (fetched via research, Sept 2026)",

    claimStatus: "unclaimed",
    verificationLevel: "unverified",
    provenance: {
      source: "Public organization website",
      method: "Manual editorial entry from cited public source",
      recordedAt: "2026-09-01",
    },
    closureStatus: "open",
    isSponsored: false,
    professionalDisclaimerShown: false,
    editorialNote:
      "Founded in Dearborn, Michigan in 1992, the American Arab Chamber of Commerce maintains an Anaheim-focused presence describing a national network of 1,800+ businesses across three local clusters: restaurants, food & retail; real estate & services; and tourism & hospitality. No stated street address was found for the Anaheim office as of this listing's creation — the chamber is listed as a service-area organization rather than a storefront.",
  },
  {
    listingId: "osm-al-noor-foundation-westminster",
    name: "Al-Noor Foundation",
    slug: "al-noor-foundation",
    primaryCategory: "faith-community",
    address: {
      street: "14522 Goldenwest Street",
      locality: "Westminster",
      region: "CA",
      postal: "92683",
    },
    hasPublicStorefront: true,
    countySlug: "orange-county",
    citySlug: "westminster",
    geo: { lat: 33.7512827, lng: -118.0064907 },

    arabOwnedSelfIdentified: "not_stated",

    faithCommunityAffiliation: "Sunni",
    claimStatus: "unclaimed",
    verificationLevel: "unverified",
    provenance: {
      source: "OpenStreetMap place-of-worship POI (ODbL)",
      method: "Automated ingestion via Overpass API",
      recordedAt: "2026-09-03",
    },
    closureStatus: "open",
    isSponsored: false,
    professionalDisclaimerShown: false,
    editorialNote: "Also known as Al-Noor Mosque. Denomination self-tagged as Sunni in OpenStreetMap.",
  },
  {
    listingId: "osm-jafaria-islamic-society-anaheim",
    name: "Jafaria Islamic Society",
    slug: "jafaria-islamic-society",
    primaryCategory: "faith-community",
    address: {
      street: "1546 East La Palma Avenue",
      locality: "Anaheim",
      region: "CA",
      postal: "92805",
    },
    hasPublicStorefront: true,
    countySlug: "orange-county",
    citySlug: "anaheim",
    website: "https://www.jafaria.org/jafaria_site/",
    geo: { lat: 33.8469003, lng: -117.8956131 },

    arabOwnedSelfIdentified: "not_stated",

    claimStatus: "unclaimed",
    verificationLevel: "unverified",
    provenance: {
      source: "OpenStreetMap place-of-worship POI (ODbL)",
      method: "Automated ingestion via Overpass API",
      recordedAt: "2026-09-03",
    },
    closureStatus: "open",
    isSponsored: false,
    professionalDisclaimerShown: false,
  },
  {
    listingId: "osm-masjid-al-ansar-anaheim",
    name: "Masjid Al-Ansar",
    slug: "masjid-al-ansar",
    primaryCategory: "faith-community",
    address: {
      street: "1717 Brookhurst Street",
      locality: "Anaheim",
      region: "CA",
      postal: "92804",
    },
    hasPublicStorefront: true,
    countySlug: "orange-county",
    citySlug: "anaheim",
    telephone: "+1-714-535-1100",
    website: "https://www.wcismasjid.com/",
    geo: { lat: 33.805618, lng: -117.9595158 },

    arabOwnedSelfIdentified: "not_stated",

    claimStatus: "unclaimed",
    verificationLevel: "unverified",
    provenance: {
      source: "OpenStreetMap place-of-worship POI (ODbL)",
      method: "Automated ingestion via Overpass API",
      recordedAt: "2026-09-03",
    },
    closureStatus: "open",
    isSponsored: false,
    professionalDisclaimerShown: false,
    editorialNote: "Located on Brookhurst Street, within the Little Arabia cultural corridor.",
  },
  {
    listingId: "osm-saint-verena-coptic-orthodox-anaheim",
    name: "Saint Verena Coptic Orthodox Church",
    slug: "saint-verena-coptic-orthodox-church",
    primaryCategory: "faith-community",
    hasPublicStorefront: true,
    countySlug: "orange-county",
    citySlug: "anaheim",
    geo: { lat: 33.8372222, lng: -117.8988889 },
    address: {
      street: "South Fahrion Place",
      locality: "Anaheim",
      region: "CA",
      postal: "92805",
    },

    arabOwnedSelfIdentified: "not_stated",

    faithCommunityAffiliation: "Coptic Orthodox",
    claimStatus: "unclaimed",
    verificationLevel: "unverified",
    provenance: {
      source: "OpenStreetMap place-of-worship POI (ODbL) + Nominatim reverse geocode for street/postal (Stage 2 enrichment, Sept 2026)",
      method: "Automated ingestion via Overpass API",
      recordedAt: "2026-09-03",
    },
    closureStatus: "open",
    isSponsored: false,
    professionalDisclaimerShown: false,
    editorialNote: "No street number was tagged on the OpenStreetMap node, so only the street name and ZIP are confirmed. An exact number is still needed before this can be treated as a mailing address.",
  },
  {
    listingId: "osm-holy-cross-melkite-placentia",
    name: "Holy Cross Melkite Greek Catholic Church",
    slug: "holy-cross-melkite-greek-catholic-church",
    primaryCategory: "faith-community",
    hasPublicStorefront: true,
    countySlug: "orange-county",
    citySlug: "placentia",
    geo: { lat: 33.8822222, lng: -117.8716667 },
    address: {
      street: "451 West Madison Avenue",
      locality: "Placentia",
      region: "CA",
      postal: "92870",
    },

    arabOwnedSelfIdentified: "not_stated",

    faithCommunityAffiliation: "Melkite Greek Catholic",
    claimStatus: "unclaimed",
    verificationLevel: "unverified",
    provenance: {
      source: "OpenStreetMap place-of-worship POI (ODbL) + Nominatim reverse geocode for street address (Stage 2 enrichment, Sept 2026)",
      method: "Automated ingestion via Overpass API",
      recordedAt: "2026-09-03",
    },
    closureStatus: "open",
    isSponsored: false,
    professionalDisclaimerShown: false,
    editorialNote: "In the Old Town Placentia neighborhood.",
  },
  {
    listingId: "osm-st-marys-syrian-orthodox-orange",
    name: "St Mary's Syrian Orthodox Church",
    slug: "st-marys-syrian-orthodox-church",
    primaryCategory: "faith-community",
    address: {
      street: "1515 East Taft Avenue",
      locality: "Orange",
      region: "CA",
      postal: "92865",
    },
    hasPublicStorefront: true,
    countySlug: "orange-county",
    citySlug: "orange",
    geo: { lat: 33.8162823, lng: -117.8380541 },

    arabOwnedSelfIdentified: "not_stated",

    faithCommunityAffiliation: "Syriac Orthodox",
    claimStatus: "unclaimed",
    verificationLevel: "unverified",
    provenance: {
      source: "OpenStreetMap place-of-worship POI (ODbL)",
      method: "Automated ingestion via Overpass API",
      recordedAt: "2026-09-03",
    },
    closureStatus: "open",
    isSponsored: false,
    professionalDisclaimerShown: false,
  },
  {
    listingId: "osm-st-paul-syriac-orthodox-santee",
    name: "St Paul Syriac Orthodox Church",
    slug: "st-paul-syriac-orthodox-church",
    primaryCategory: "faith-community",
    hasPublicStorefront: true,
    countySlug: "san-diego-county",
    citySlug: "santee",
    geo: { lat: 32.8372717, lng: -116.973916 },
    address: {
      street: "Cottonwood Avenue",
      locality: "Santee",
      region: "CA",
      postal: "92022",
    },

    arabOwnedSelfIdentified: "not_stated",

    faithCommunityAffiliation: "Syriac Orthodox",
    claimStatus: "unclaimed",
    verificationLevel: "unverified",
    provenance: {
      source: "OpenStreetMap place-of-worship POI (ODbL) + Nominatim reverse geocode for street/postal (Stage 2 enrichment, Sept 2026)",
      method: "Automated ingestion via Overpass API",
      recordedAt: "2026-09-03",
    },
    closureStatus: "open",
    isSponsored: false,
    professionalDisclaimerShown: false,
    editorialNote: "No street number was tagged on the OpenStreetMap node, so only the street name and ZIP are confirmed.",
  },
  {
    listingId: "osm-al-rribat-al-aslami-la-mesa",
    name: "Al Rribat Al Aslami",
    slug: "al-rribat-al-aslami",
    primaryCategory: "faith-community",
    hasPublicStorefront: true,
    countySlug: "san-diego-county",
    citySlug: "la-mesa",
    geo: { lat: 32.7708073, lng: -117.043655 },
    address: {
      street: "Saranac Street",
      locality: "La Mesa",
      region: "CA",
      postal: "92112",
    },

    arabOwnedSelfIdentified: "not_stated",

    claimStatus: "unclaimed",
    verificationLevel: "unverified",
    provenance: {
      source: "OpenStreetMap place-of-worship POI (ODbL) + Nominatim reverse geocode for street/postal (Stage 2 enrichment, Sept 2026)",
      method: "Automated ingestion via Overpass API",
      recordedAt: "2026-09-03",
    },
    closureStatus: "open",
    isSponsored: false,
    professionalDisclaimerShown: false,
    editorialNote: "OpenStreetMap itself flags this record with a \"check religion\" note (its own contributor-added fixme tag), so treat the Islamic-center classification as unconfirmed until verified. No street number was tagged, and Nominatim's reverse geocode files this address under San Diego's unincorporated mail-service area rather than La Mesa's own ZIP — kept under La Mesa here since that's the nearest incorporated city, but worth confirming on claim.",
  },
  {
    listingId: "osm-saint-michael-chaldean-el-cajon",
    name: "Saint Michael Chaldean Catholic Church",
    slug: "saint-michael-chaldean-catholic-church",
    primaryCategory: "faith-community",
    hasPublicStorefront: true,
    countySlug: "san-diego-county",
    citySlug: "el-cajon",
    geo: { lat: 32.7876978, lng: -116.9522952 },
    address: {
      street: "East Washington Avenue",
      locality: "El Cajon",
      region: "CA",
      postal: "92020",
    },

    arabOwnedSelfIdentified: "not_stated",

    faithCommunityAffiliation: "Chaldean Catholic",
    claimStatus: "unclaimed",
    verificationLevel: "unverified",
    provenance: {
      source: "OpenStreetMap place-of-worship POI (ODbL) + Nominatim reverse geocode for street/postal (Stage 2 enrichment, Sept 2026)",
      method: "Automated ingestion via Overpass API",
      recordedAt: "2026-09-03",
    },
    closureStatus: "open",
    isSponsored: false,
    professionalDisclaimerShown: false,
    editorialNote: "In the heart of San Diego County's Chaldean/Iraqi-majority community per the blueprint's demographic research. No street number was tagged on the OpenStreetMap node, so only the street name and ZIP are confirmed.",
  },
  {
    listingId: "osm-islamic-center-of-lakeside",
    name: "Islamic Center of Lakeside",
    slug: "islamic-center-of-lakeside",
    primaryCategory: "faith-community",
    hasPublicStorefront: true,
    countySlug: "san-diego-county",
    citySlug: "lakeside",
    geo: { lat: 32.865053, lng: -116.956789 },
    address: {
      street: "Mountain View Lane",
      locality: "Lakeside",
      region: "CA",
      postal: "92071",
    },

    arabOwnedSelfIdentified: "not_stated",

    claimStatus: "unclaimed",
    verificationLevel: "unverified",
    provenance: {
      source: "OpenStreetMap place-of-worship POI (ODbL) + Nominatim reverse geocode for street/postal (Stage 2 enrichment, Sept 2026)",
      method: "Automated ingestion via Overpass API",
      recordedAt: "2026-09-03",
    },
    closureStatus: "open",
    isSponsored: false,
    professionalDisclaimerShown: false,
    editorialNote: "No street number was tagged on the OpenStreetMap node, so only the street name and ZIP are confirmed.",
  },
  {
    listingId: "osm-our-mother-of-perpetual-help-el-cajon",
    name: "Our Mother of Perpetual Help",
    slug: "our-mother-of-perpetual-help",
    primaryCategory: "faith-community",
    hasPublicStorefront: true,
    countySlug: "san-diego-county",
    citySlug: "el-cajon",
    geo: { lat: 32.7798922, lng: -116.950317 },
    address: {
      street: "South Mollison Avenue (near 1025)",
      locality: "El Cajon",
      region: "CA",
      postal: "92020",
    },

    arabOwnedSelfIdentified: "not_stated",

    faithCommunityAffiliation: "Syriac Catholic",
    claimStatus: "unclaimed",
    verificationLevel: "unverified",
    provenance: {
      source: "OpenStreetMap place-of-worship POI (ODbL) + Nominatim reverse geocode for street/postal (Stage 2 enrichment, Sept 2026)",
      method: "Automated ingestion via Overpass API",
      recordedAt: "2026-09-03",
    },
    closureStatus: "open",
    isSponsored: false,
    professionalDisclaimerShown: false,
    editorialNote: "The church itself has no address tagged in OpenStreetMap; the number shown is the nearest addressed parcel returned by reverse geocoding its coordinates, not a confirmed street number for the church — treat it as approximate until an owner claims this listing.",
  },
  {
    listingId: "osm-luna-grill-el-cajon",
    name: "Luna Grill",
    slug: "luna-grill-el-cajon",
    primaryCategory: "food-drink",
    address: {
      street: "2963 Jamacha Road",
      locality: "El Cajon",
      region: "CA",
      postal: "92019",
    },
    hasPublicStorefront: true,
    countySlug: "san-diego-county",
    citySlug: "el-cajon",
    telephone: "+1-619-797-4000",
    website: "https://locations.lunagrill.com/luna-grill-e09db7a47093",
    geo: { lat: 32.7377885, lng: -116.9398908 },

    arabOwnedSelfIdentified: "not_stated",

    claimStatus: "unclaimed",
    verificationLevel: "unverified",
    provenance: {
      source: "OpenStreetMap POI (ODbL)",
      method: "Automated ingestion via Overpass API",
      recordedAt: "2026-09-03",
    },
    closureStatus: "open",
    isSponsored: false,
    professionalDisclaimerShown: false,
    editorialNote: "Mediterranean-cuisine restaurant chain location. Cuisine tag only — no ownership or halal-certification claim is made or implied by this listing.",
  },
  {
    listingId: "osm-sahara-el-cajon",
    name: "Sahara",
    slug: "sahara-el-cajon",
    primaryCategory: "food-drink",
    address: {
      street: "2990 Jamacha Road",
      locality: "El Cajon",
      region: "CA",
      postal: "92019",
    },
    hasPublicStorefront: true,
    countySlug: "san-diego-county",
    citySlug: "el-cajon",
    telephone: "+1-619-660-9990",
    website: "https://saharasd.com/",
    geo: { lat: 32.7403701, lng: -116.9422469 },

    arabOwnedSelfIdentified: "not_stated",

    claimStatus: "unclaimed",
    verificationLevel: "unverified",
    provenance: {
      source: "OpenStreetMap POI (ODbL)",
      method: "Automated ingestion via Overpass API",
      recordedAt: "2026-09-03",
    },
    closureStatus: "open",
    isSponsored: false,
    professionalDisclaimerShown: false,
    editorialNote: "Tagged in OpenStreetMap as Middle Eastern / Mediterranean cuisine. No ownership or halal-certification claim is made or implied by this listing.",
  },
  {
    listingId: "osm-family-golden-palace-el-cajon",
    name: "Family Golden Palace",
    slug: "family-golden-palace-el-cajon",
    primaryCategory: "food-drink",
    address: {
      street: "820 Jamacha Road",
      locality: "El Cajon",
      region: "CA",
      postal: "92019",
    },
    hasPublicStorefront: true,
    countySlug: "san-diego-county",
    citySlug: "el-cajon",
    telephone: "+1-619-332-8833",
    geo: { lat: 32.784867, lng: -116.928286 },

    arabOwnedSelfIdentified: "not_stated",

    claimStatus: "unclaimed",
    verificationLevel: "unverified",
    provenance: {
      source: "OpenStreetMap POI (ODbL); phone cross-checked against independent public business directories (Stage 2 enrichment, Sept 2026) — no official business website was found",
      method: "Automated ingestion via Overpass API",
      recordedAt: "2026-09-03",
    },
    closureStatus: "open",
    isSponsored: false,
    professionalDisclaimerShown: false,
    editorialNote: "Tagged in OpenStreetMap as Mediterranean cuisine. No ownership or halal-certification claim is made or implied by this listing. No official business website found — the phone number is from third-party directory listings, not the business's own site, so treat it as unconfirmed until claimed.",
  },
  {
    listingId: "osm-mal-al-sham-el-cajon",
    name: "Mal Al Sham",
    slug: "mal-al-sham-el-cajon",
    primaryCategory: "food-drink",
    address: {
      street: "388 East Main Street",
      locality: "El Cajon",
      region: "CA",
      postal: "92020",
    },
    hasPublicStorefront: true,
    countySlug: "san-diego-county",
    citySlug: "el-cajon",
    telephone: "+1-619-401-1055",
    website: "https://malalsham.com/",
    openingHours: "Sun–Thu 9:00 AM–10:00 PM; Fri–Sat 9:00 AM–Midnight",
    geo: { lat: 32.7952599, lng: -116.9575009 },

    arabOwnedSelfIdentified: "not_stated",

    claimStatus: "unclaimed",
    verificationLevel: "unverified",
    provenance: {
      source: "OpenStreetMap POI (ODbL) + business's own website (malalsham.com) for phone number and hours (Stage 2 enrichment, Sept 2026)",
      method: "Automated ingestion via Overpass API, cross-checked against the business's own site",
      recordedAt: "2026-09-13",
    },
    closureStatus: "open",
    isSponsored: false,
    professionalDisclaimerShown: false,
    editorialNote: "Tagged in OpenStreetMap as Syrian cuisine; self-described on the business's own site as \"The Taste of Damascus.\" No ownership or halal-certification claim is made or implied by this listing.",
  },
  {
    listingId: "web-abn-al-sham-el-cajon",
    name: "Abn Al Sham",
    slug: "abn-al-sham-el-cajon",
    primaryCategory: "food-drink",
    address: {
      street: "8575 Los Coches Road, Unit 10",
      locality: "El Cajon",
      region: "CA",
      postal: "92021",
    },
    hasPublicStorefront: true,
    countySlug: "san-diego-county",
    citySlug: "el-cajon",
    telephone: "+1-619-938-4707",
    website: "https://abnalsham.top/",
    openingHours: "Daily 11:00 AM–11:00 PM",

    arabOwnedSelfIdentified: "not_stated",

    claimStatus: "unclaimed",
    verificationLevel: "unverified",
    provenance: {
      source: "Business's own website (abnalsham.top) for address, phone, and hours — not yet tagged in OpenStreetMap as of Sept 2026",
      method: "Manual editorial entry, discovered via general web search and verified directly against the business's own site (no data taken from Google Maps or Yelp)",
      recordedAt: "2026-09-13",
    },
    closureStatus: "open",
    isSponsored: false,
    professionalDisclaimerShown: false,
    editorialNote: "Mediterranean/Levantine restaurant. No ownership or halal-certification claim is made or implied by this listing. No geo coordinates yet since it is not present in OpenStreetMap.",
  },
  {
    listingId: "osm-mr-shawarma-el-cajon",
    name: "Mr. Shawarma",
    slug: "mr-shawarma-el-cajon",
    primaryCategory: "food-drink",
    hasPublicStorefront: false,
    serviceArea: ["El Cajon, CA", "San Diego County, CA"],
    countySlug: "san-diego-county",
    citySlug: "el-cajon",
    telephone: "+1-619-558-6311",
    website: "https://mrshawarmatrucks.com/",

    arabOwnedSelfIdentified: "not_stated",
    halalStatus: "self_described_halal",

    claimStatus: "unclaimed",
    verificationLevel: "unverified",
    provenance: {
      source: "OpenStreetMap POI (ODbL); diet:halal=yes is a community-reported OSM tag, not a formal certification",
      method: "Automated ingestion via Overpass API",
      recordedAt: "2026-09-13",
    },
    closureStatus: "open",
    isSponsored: false,
    professionalDisclaimerShown: false,
    editorialNote: "Operates as a food truck with rotating stop locations around El Cajon rather than one fixed storefront — this explains the conflicting street addresses found across different delivery/review platforms during research, so no single fixed address is listed here. Halal status is self-described (community-tagged in OpenStreetMap), not an authority certification.",
  },
  {
    listingId: "web-kabul-kabob-house-el-cajon",
    name: "Kabul Kabob House",
    slug: "kabul-kabob-house-el-cajon",
    primaryCategory: "food-drink",
    address: {
      street: "1255 East Main Street, Suite A",
      locality: "El Cajon",
      region: "CA",
      postal: "92021",
    },
    hasPublicStorefront: true,
    countySlug: "san-diego-county",
    citySlug: "el-cajon",
    telephone: "+1-619-357-6137",
    website: "https://kabulkabobsd.com/",
    openingHours: "Mon–Sun 10:00 AM–10:00 PM (dine-in service until 9:30 PM)",
    geo: { lat: 32.7945145, lng: -116.9391268 },

    arabOwnedSelfIdentified: "not_stated",
    halalStatus: "self_described_halal",

    claimStatus: "unclaimed",
    verificationLevel: "unverified",
    provenance: {
      source: "OpenStreetMap POI (ODbL) + business's own website (kabulkabobsd.com) for address, phone, and hours (Stage 2 enrichment, Sept 2026)",
      method: "Automated ingestion via Overpass API, cross-checked against the business's own site",
      recordedAt: "2026-09-13",
    },
    closureStatus: "open",
    isSponsored: false,
    professionalDisclaimerShown: false,
    editorialNote: "Afghan restaurant (kebab cuisine), included at the site owner's request. Afghanistan is not an Arab country and Dari/Pashto are not Arabic, so no Arab-community affiliation is implied by this listing — it is included here as a Middle Eastern/kebab-cuisine restaurant, not as part of the Arab American or Arabic-speaking community coverage described elsewhere on the site. Halal status is self-described (community-tagged in OpenStreetMap), not an authority certification.",
  },
  {
    listingId: "osm-al-sultan-mediterranean-grill",
    name: "Al-Sultan Mediterranean Grill",
    slug: "al-sultan-mediterranean-grill",
    primaryCategory: "food-drink",
    address: {
      street: "1707 South Brookhurst Street",
      locality: "Anaheim",
      region: "CA",
      postal: "92802",
    },
    hasPublicStorefront: true,
    countySlug: "orange-county",
    citySlug: "anaheim",
    telephone: "+1-714-844-2093",
    website: "https://alsultanmediterraneangrillca.com/",
    geo: { lat: 33.8059448, lng: -117.9594385 },

    arabOwnedSelfIdentified: "not_stated",

    halalStatus: "self_described_halal",
    claimStatus: "unclaimed",
    verificationLevel: "unverified",
    provenance: {
      source: "OpenStreetMap POI (ODbL)",
      method: "Automated ingestion via Overpass API",
      recordedAt: "2026-09-03",
    },
    closureStatus: "open",
    isSponsored: false,
    professionalDisclaimerShown: false,
    editorialNote: "Cuisine tagged shawarma/Mediterranean; OpenStreetMap's diet:halal=yes tag is a community-reported signal, not a formal certification, so this is recorded as self-described rather than authority-certified.",
  },
  {
    listingId: "osm-forn-al-hara",
    name: "Forn Al Hara",
    slug: "forn-al-hara",
    primaryCategory: "food-drink",
    address: {
      street: "512 South Brookhurst Street, Unit 6",
      locality: "Anaheim",
      region: "CA",
      postal: "92804",
    },
    hasPublicStorefront: true,
    countySlug: "orange-county",
    citySlug: "anaheim",
    telephone: "+1-714-758-3777",
    website: "https://fornalhara.com/",
    geo: { lat: 33.8260487, lng: -117.9582242 },

    arabOwnedSelfIdentified: "not_stated",

    claimStatus: "unclaimed",
    verificationLevel: "unverified",
    provenance: {
      source: "OpenStreetMap POI (ODbL)",
      method: "Automated ingestion via Overpass API",
      recordedAt: "2026-09-03",
    },
    closureStatus: "open",
    isSponsored: false,
    professionalDisclaimerShown: false,
    editorialNote: "Cuisine tagged Arab/Lebanese/Mediterranean in OpenStreetMap. Part of the South Brookhurst Street plaza (512/518) within the Little Arabia corridor.",
  },
  {
    listingId: "osm-house-of-mandi",
    name: "House of Mandi",
    slug: "house-of-mandi",
    primaryCategory: "food-drink",
    address: {
      street: "518 South Brookhurst Street, Unit 1",
      locality: "Anaheim",
      region: "CA",
      postal: "92804",
    },
    hasPublicStorefront: true,
    countySlug: "orange-county",
    citySlug: "anaheim",
    telephone: "+1-657-220-5272",
    website: "https://www.houseofmandianaheim.com/",
    geo: { lat: 33.8256065, lng: -117.9586727 },

    arabOwnedSelfIdentified: "not_stated",

    claimStatus: "unclaimed",
    verificationLevel: "unverified",
    provenance: {
      source: "OpenStreetMap POI (ODbL)",
      method: "Automated ingestion via Overpass API",
      recordedAt: "2026-09-03",
    },
    closureStatus: "open",
    isSponsored: false,
    professionalDisclaimerShown: false,
    editorialNote: "Cuisine tagged Arab in OpenStreetMap (mandi is a rice-and-meat dish associated with the Arabian Peninsula and Yemen). Part of the South Brookhurst Street plaza within the Little Arabia corridor.",
  },
  {
    listingId: "osm-jamila-juice",
    name: "Jamila Juice",
    slug: "jamila-juice",
    primaryCategory: "food-drink",
    address: {
      street: "512 South Brookhurst Street, Unit 4",
      locality: "Anaheim",
      region: "CA",
      postal: "92804",
    },
    hasPublicStorefront: true,
    countySlug: "orange-county",
    citySlug: "anaheim",
    telephone: "+1-714-215-4499",
    website: "https://www.jamilajuice.com/",
    geo: { lat: 33.8260523, lng: -117.958386 },

    arabOwnedSelfIdentified: "not_stated",

    claimStatus: "unclaimed",
    verificationLevel: "unverified",
    provenance: {
      source: "OpenStreetMap POI (ODbL)",
      method: "Automated ingestion via Overpass API",
      recordedAt: "2026-09-03",
    },
    closureStatus: "open",
    isSponsored: false,
    professionalDisclaimerShown: false,
    editorialNote: "Part of the South Brookhurst Street plaza within the Little Arabia corridor.",
  },
  {
    listingId: "osm-qahwah-and-chapati",
    name: "Qahwah & Chauati",
    slug: "qahwah-and-chauati",
    primaryCategory: "food-drink",
    address: {
      street: "518 South Brookhurst Street, Unit 3",
      locality: "Anaheim",
      region: "CA",
      postal: "92804",
    },
    hasPublicStorefront: true,
    countySlug: "orange-county",
    citySlug: "anaheim",
    telephone: "+1-714-833-5818",
    website: "https://www.qahwahandchapati.com/",
    geo: { lat: 33.8256173, lng: -117.9585357 },

    arabOwnedSelfIdentified: "not_stated",

    claimStatus: "unclaimed",
    verificationLevel: "unverified",
    provenance: {
      source: "OpenStreetMap POI (ODbL)",
      method: "Automated ingestion via Overpass API",
      recordedAt: "2026-09-03",
    },
    closureStatus: "open",
    isSponsored: false,
    professionalDisclaimerShown: false,
    editorialNote: "Name spelling taken as-tagged in OpenStreetMap (\"Qahwah\" is Arabic for coffee); the linked website spells it \"Chapati\" — worth confirming the exact name before this listing is claimed. Part of the South Brookhurst Street plaza within the Little Arabia corridor.",
  },
  {
    listingId: "osm-jenin-meat-market",
    name: "Jenin Meat Market",
    slug: "jenin-meat-market",
    primaryCategory: "food-drink",
    address: {
      street: "518 South Brookhurst Street, Unit 6",
      locality: "Anaheim",
      region: "CA",
      postal: "92804",
    },
    hasPublicStorefront: true,
    countySlug: "orange-county",
    citySlug: "anaheim",
    telephone: "+1-714-215-4149",
    website: "https://www.jeninmeatmarket.com/",
    geo: { lat: 33.8256173, lng: -117.9582369 },

    arabOwnedSelfIdentified: "not_stated",

    claimStatus: "unclaimed",
    verificationLevel: "unverified",
    provenance: {
      source: "OpenStreetMap POI (ODbL)",
      method: "Automated ingestion via Overpass API",
      recordedAt: "2026-09-03",
    },
    closureStatus: "open",
    isSponsored: false,
    professionalDisclaimerShown: false,
    editorialNote: "Named for Jenin, a city in the West Bank. Part of the South Brookhurst Street plaza within the Little Arabia corridor.",
  },
  {
    listingId: "osm-sababa-falafel-shop",
    name: "Sababa Falafel Shop",
    slug: "sababa-falafel-shop",
    primaryCategory: "food-drink",
    hasPublicStorefront: true,
    countySlug: "orange-county",
    citySlug: "garden-grove",
    geo: { lat: 33.8026228, lng: -117.9593587 },
    address: {
      street: "11011 Brookhurst Street",
      locality: "Garden Grove",
      region: "CA",
      postal: "92840",
    },
    website: "https://www.sababafalafelshop.com/",
    openingHours: "Mon–Sat 10:00 am–10:00 pm, Sun 10:00 am–8:00 pm",

    arabOwnedSelfIdentified: "not_stated",

    halalStatus: "self_described_halal",
    claimStatus: "unclaimed",
    verificationLevel: "unverified",
    provenance: {
      source: "OpenStreetMap POI (ODbL) + business's own website (sababafalafelshop.com) for address, hours, and halal claim (Stage 2 enrichment, Sept 2026)",
      method: "Automated ingestion via Overpass API, cross-checked against the business's own site",
      recordedAt: "2026-09-03",
    },
    closureStatus: "open",
    isSponsored: false,
    professionalDisclaimerShown: false,
    editorialNote: "Originally geocoded to Anaheim from OpenStreetMap coordinates alone; the business's own website gives its address as Garden Grove, just south of the Little Arabia corridor along the same Brookhurst Street strip, so the city has been corrected here. Its own site states its meats and chicken are \"certified by Islamic authorities\" without naming the certifying body, so this is recorded as a self-described halal claim rather than an authority-verified certification. No phone number is published on the business's own site.",
  },

  // --- Los Angeles County (Phase 3), added Sept 2026 via the same OpenStreetMap Overpass +
  // Nominatim method used for Orange and San Diego counties. Population here is highly
  // dispersed (per the blueprint's demographic research), so this pass spans several
  // incorporated cities across the county rather than one corridor.
  {
    listingId: "osm-saint-mark-coptic-la",
    name: "Saint Mark Coptic Orthodox Church",
    slug: "saint-mark-coptic-orthodox-church",
    primaryCategory: "faith-community",
    hasPublicStorefront: true,
    countySlug: "los-angeles-county",
    citySlug: "los-angeles",
    geo: { lat: 34.0503571, lng: -118.3841612 },
    address: {
      street: "Pickford Street",
      locality: "Los Angeles",
      region: "CA",
      postal: "90035",
    },

    arabOwnedSelfIdentified: "not_stated",

    faithCommunityAffiliation: "Coptic Orthodox",
    claimStatus: "unclaimed",
    verificationLevel: "unverified",
    provenance: {
      source: "OpenStreetMap place-of-worship POI (ODbL) + Nominatim reverse geocode for street/postal",
      method: "Automated ingestion via Overpass API",
      recordedAt: "2026-09-04",
    },
    closureStatus: "open",
    isSponsored: false,
    professionalDisclaimerShown: false,
    editorialNote: "In the Pico-Robertson neighborhood. No street number was tagged on the OpenStreetMap node, so only the street name and ZIP are confirmed.",
  },
  {
    listingId: "osm-islamic-center-hawthorne",
    name: "Islamic Center of Hawthorne",
    slug: "islamic-center-of-hawthorne",
    primaryCategory: "faith-community",
    hasPublicStorefront: true,
    countySlug: "los-angeles-county",
    citySlug: "hawthorne",
    geo: { lat: 33.9213889, lng: -118.3538889 },
    address: {
      street: "Hawthorne Way",
      locality: "Hawthorne",
      region: "CA",
      postal: "90250",
    },

    arabOwnedSelfIdentified: "not_stated",

    claimStatus: "unclaimed",
    verificationLevel: "unverified",
    provenance: {
      source: "OpenStreetMap place-of-worship POI (ODbL) + Nominatim reverse geocode for street/postal",
      method: "Automated ingestion via Overpass API",
      recordedAt: "2026-09-04",
    },
    closureStatus: "open",
    isSponsored: false,
    professionalDisclaimerShown: false,
    editorialNote: "No street number was tagged on the OpenStreetMap node, so only the street name and ZIP are confirmed.",
  },
  {
    listingId: "osm-islamic-center-inglewood",
    name: "Islamic Center of Inglewood",
    slug: "islamic-center-of-inglewood",
    primaryCategory: "faith-community",
    hasPublicStorefront: true,
    countySlug: "los-angeles-county",
    citySlug: "inglewood",
    geo: { lat: 33.9530392, lng: -118.3509708 },
    address: {
      street: "Arbor Vitae Street",
      locality: "Inglewood",
      region: "CA",
      postal: "90301",
    },

    arabOwnedSelfIdentified: "not_stated",

    claimStatus: "unclaimed",
    verificationLevel: "unverified",
    provenance: {
      source: "OpenStreetMap place-of-worship POI (ODbL) + Nominatim reverse geocode for street/postal",
      method: "Automated ingestion via Overpass API",
      recordedAt: "2026-09-04",
    },
    closureStatus: "open",
    isSponsored: false,
    professionalDisclaimerShown: false,
    editorialNote: "No street number was tagged on the OpenStreetMap node, so only the street name and ZIP are confirmed.",
  },
  {
    listingId: "osm-king-fahad-mosque-culver-city",
    name: "King Fahad Mosque",
    slug: "king-fahad-mosque",
    primaryCategory: "faith-community",
    hasPublicStorefront: true,
    countySlug: "los-angeles-county",
    citySlug: "culver-city",
    geo: { lat: 34.0115344, lng: -118.4102487 },
    address: {
      street: "Washington Boulevard",
      locality: "Culver City",
      region: "CA",
      postal: "90232",
    },

    arabOwnedSelfIdentified: "not_stated",

    claimStatus: "unclaimed",
    verificationLevel: "unverified",
    provenance: {
      source: "OpenStreetMap place-of-worship POI (ODbL) + Nominatim reverse geocode for street/postal",
      method: "Automated ingestion via Overpass API",
      recordedAt: "2026-09-04",
    },
    closureStatus: "open",
    isSponsored: false,
    professionalDisclaimerShown: false,
    editorialNote: "One of the larger, better-known mosques on LA's Westside. No street number was tagged on the OpenStreetMap node, so only the street name and ZIP are confirmed.",
  },
  {
    listingId: "osm-saint-peter-paul-coptic-santa-monica",
    name: "Saint Peter and Saint Paul Coptic Orthodox Church",
    slug: "saint-peter-and-saint-paul-coptic-orthodox-church",
    primaryCategory: "faith-community",
    hasPublicStorefront: true,
    countySlug: "los-angeles-county",
    citySlug: "santa-monica",
    geo: { lat: 34.0182229, lng: -118.4970169 },
    address: {
      street: "4th Street",
      locality: "Santa Monica",
      region: "CA",
      postal: "90401",
    },

    arabOwnedSelfIdentified: "not_stated",

    faithCommunityAffiliation: "Coptic Orthodox",
    claimStatus: "unclaimed",
    verificationLevel: "unverified",
    provenance: {
      source: "OpenStreetMap place-of-worship POI (ODbL) + Nominatim reverse geocode for street/postal",
      method: "Automated ingestion via Overpass API",
      recordedAt: "2026-09-04",
    },
    closureStatus: "open",
    isSponsored: false,
    professionalDisclaimerShown: false,
    editorialNote: "In Downtown Santa Monica. No street number was tagged on the OpenStreetMap node, so only the street name and ZIP are confirmed.",
  },
  {
    listingId: "osm-masjid-bilal-la",
    name: "Masjid Bilal",
    slug: "masjid-bilal",
    primaryCategory: "faith-community",
    hasPublicStorefront: true,
    countySlug: "los-angeles-county",
    citySlug: "los-angeles",
    geo: { lat: 34.0109468, lng: -118.2562323 },
    address: {
      street: "East Martin Luther King Jr. Boulevard",
      locality: "Los Angeles",
      region: "CA",
      postal: "90011",
    },

    arabOwnedSelfIdentified: "not_stated",

    claimStatus: "unclaimed",
    verificationLevel: "unverified",
    provenance: {
      source: "OpenStreetMap place-of-worship POI (ODbL) + Nominatim reverse geocode for street/postal",
      method: "Automated ingestion via Overpass API",
      recordedAt: "2026-09-04",
    },
    closureStatus: "open",
    isSponsored: false,
    professionalDisclaimerShown: false,
    editorialNote: "In the Central-Alameda neighborhood, South LA. No street number was tagged on the OpenStreetMap node, so only the street name and ZIP are confirmed.",
  },
  {
    listingId: "osm-arabic-bible-christian-church-long-beach",
    name: "Arabic Bible Christian Church",
    slug: "arabic-bible-christian-church",
    primaryCategory: "faith-community",
    hasPublicStorefront: true,
    countySlug: "los-angeles-county",
    citySlug: "long-beach",
    geo: { lat: 33.7679434, lng: -118.1566097 },
    address: {
      street: "East 3rd Street",
      locality: "Long Beach",
      region: "CA",
      postal: "90814",
    },
    website: "https://abcc.org/",

    arabOwnedSelfIdentified: "not_stated",

    claimStatus: "unclaimed",
    verificationLevel: "unverified",
    provenance: {
      source: "OpenStreetMap place-of-worship POI (ODbL) + Nominatim reverse geocode for street/postal",
      method: "Automated ingestion via Overpass API",
      recordedAt: "2026-09-04",
    },
    closureStatus: "open",
    isSponsored: false,
    professionalDisclaimerShown: false,
    editorialNote: "In the Belmont Shore neighborhood. OpenStreetMap did not tag a specific denomination for this church, and no street number was tagged either, so only the street name and ZIP are confirmed.",
  },
  {
    listingId: "osm-almaza-restaurant-hookah-la",
    name: "Almaza Restaurant and Hookah",
    slug: "almaza-restaurant-and-hookah",
    primaryCategory: "food-drink",
    address: {
      street: "8905 Venice Boulevard",
      locality: "Los Angeles",
      region: "CA",
      postal: "90034",
    },
    hasPublicStorefront: true,
    countySlug: "los-angeles-county",
    citySlug: "los-angeles",
    geo: { lat: 34.0290898, lng: -118.3893500 },

    arabOwnedSelfIdentified: "not_stated",

    claimStatus: "unclaimed",
    verificationLevel: "unverified",
    provenance: {
      source: "OpenStreetMap POI (ODbL)",
      method: "Automated ingestion via Overpass API",
      recordedAt: "2026-09-04",
    },
    closureStatus: "open",
    isSponsored: false,
    professionalDisclaimerShown: false,
    editorialNote: "In the Palms neighborhood. Tagged in OpenStreetMap as Middle Eastern cuisine with hookah service. No ownership or halal-certification claim is made or implied by this listing.",
  },
  {
    listingId: "osm-tarboosh-middle-east-kitchen-la",
    name: "Tarboosh Middle East Kitchen",
    slug: "tarboosh-middle-east-kitchen",
    primaryCategory: "food-drink",
    address: {
      street: "Wilshire Boulevard",
      locality: "Los Angeles",
      region: "CA",
      postal: "90010",
    },
    hasPublicStorefront: true,
    countySlug: "los-angeles-county",
    citySlug: "los-angeles",
    geo: { lat: 34.0619429, lng: -118.2987300 },

    arabOwnedSelfIdentified: "not_stated",

    claimStatus: "unclaimed",
    verificationLevel: "unverified",
    provenance: {
      source: "OpenStreetMap POI (ODbL) + Nominatim reverse geocode for street/postal",
      method: "Automated ingestion via Overpass API",
      recordedAt: "2026-09-04",
    },
    closureStatus: "open",
    isSponsored: false,
    professionalDisclaimerShown: false,
    editorialNote: "In Koreatown. Tagged in OpenStreetMap as Middle Eastern cuisine. No street number was tagged, and no phone or website found. No ownership or halal-certification claim is made or implied by this listing.",
  },
  {
    listingId: "osm-falafel-arax-glendale",
    name: "Falafel Arax",
    slug: "falafel-arax",
    primaryCategory: "food-drink",
    address: {
      street: "625 East Colorado Street",
      locality: "Glendale",
      region: "CA",
      postal: "91205",
    },
    hasPublicStorefront: true,
    countySlug: "los-angeles-county",
    citySlug: "glendale",
    telephone: "+1-818-696-2303",
    website: "https://falafelaraxusa.com/",
    openingHours: "Mon–Sat 11:00 am–10:00 pm, Sun 11:00 am–8:00 pm",
    geo: { lat: 34.1430190, lng: -118.2473965 },

    arabOwnedSelfIdentified: "not_stated",

    claimStatus: "unclaimed",
    verificationLevel: "unverified",
    provenance: {
      source: "OpenStreetMap POI (ODbL)",
      method: "Automated ingestion via Overpass API",
      recordedAt: "2026-09-04",
    },
    closureStatus: "open",
    isSponsored: false,
    professionalDisclaimerShown: false,
    editorialNote: "Tagged in OpenStreetMap as Mediterranean/falafel/Middle Eastern cuisine. No ownership or halal-certification claim is made or implied by this listing.",
  },
  {
    listingId: "osm-saffys-la",
    name: "Saffy's",
    slug: "saffys",
    primaryCategory: "food-drink",
    address: {
      street: "4845 Fountain Avenue",
      locality: "Los Angeles",
      region: "CA",
      postal: "90029",
    },
    hasPublicStorefront: true,
    countySlug: "los-angeles-county",
    citySlug: "los-angeles",
    telephone: "+1-424-699-4845",
    website: "https://www.saffysla.com/",
    geo: { lat: 34.0956189, lng: -118.2952152 },

    arabOwnedSelfIdentified: "not_stated",

    halalStatus: "self_described_halal",
    claimStatus: "unclaimed",
    verificationLevel: "unverified",
    provenance: {
      source: "OpenStreetMap POI (ODbL)",
      method: "Automated ingestion via Overpass API",
      recordedAt: "2026-09-04",
    },
    closureStatus: "open",
    isSponsored: false,
    professionalDisclaimerShown: false,
    editorialNote: "Tagged in OpenStreetMap as Arabic/kebab cuisine with diet:halal=yes, which is a community-reported signal rather than a named certifying body, so recorded as self-described. No ownership claim is made or implied by this listing.",
  },
  {
    listingId: "osm-open-sesame-la",
    name: "Open Sesame",
    slug: "open-sesame",
    primaryCategory: "food-drink",
    address: {
      street: "7458 Beverly Boulevard",
      locality: "Los Angeles",
      region: "CA",
      postal: "90036",
    },
    hasPublicStorefront: true,
    countySlug: "los-angeles-county",
    citySlug: "los-angeles",
    telephone: "+1-323-525-1698",
    website: "https://www.opensesamecafe.com/",
    geo: { lat: 34.0759555, lng: -118.3526233 },

    arabOwnedSelfIdentified: "not_stated",

    claimStatus: "unclaimed",
    verificationLevel: "unverified",
    provenance: {
      source: "OpenStreetMap POI (ODbL)",
      method: "Automated ingestion via Overpass API",
      recordedAt: "2026-09-04",
    },
    closureStatus: "open",
    isSponsored: false,
    professionalDisclaimerShown: false,
    editorialNote: "Tagged in OpenStreetMap as Mediterranean/Lebanese cuisine. No ownership or halal-certification claim is made or implied by this listing.",
  },
  {
    listingId: "osm-hasiba-la",
    name: "Hasiba",
    slug: "hasiba",
    primaryCategory: "food-drink",
    address: {
      street: "8532 West Pico Boulevard",
      locality: "Los Angeles",
      region: "CA",
      postal: "90064",
    },
    hasPublicStorefront: true,
    countySlug: "los-angeles-county",
    citySlug: "los-angeles",
    telephone: "+1-424-302-0225",
    geo: { lat: 34.0533292, lng: -118.3770175 },

    arabOwnedSelfIdentified: "not_stated",

    claimStatus: "unclaimed",
    verificationLevel: "unverified",
    provenance: {
      source: "OpenStreetMap POI (ODbL) + Nominatim reverse geocode for street/postal",
      method: "Automated ingestion via Overpass API",
      recordedAt: "2026-09-04",
    },
    closureStatus: "open",
    isSponsored: false,
    professionalDisclaimerShown: false,
    editorialNote: "In the South Carthay/Pico-Robertson area. Tagged in OpenStreetMap as Middle Eastern cuisine, sidewalk seating. No official website found. No ownership or halal-certification claim is made or implied by this listing.",
  },
  {
    listingId: "osm-kabob-house-reseda",
    name: "Kabob House",
    slug: "kabob-house-reseda",
    primaryCategory: "food-drink",
    address: {
      street: "Reseda Boulevard",
      locality: "Los Angeles",
      region: "CA",
      postal: "91335",
    },
    hasPublicStorefront: true,
    countySlug: "los-angeles-county",
    citySlug: "los-angeles",
    geo: { lat: 34.1870450, lng: -118.5363172 },

    arabOwnedSelfIdentified: "not_stated",

    claimStatus: "unclaimed",
    verificationLevel: "unverified",
    provenance: {
      source: "OpenStreetMap POI (ODbL) + Nominatim reverse geocode for street/postal",
      method: "Automated ingestion via Overpass API",
      recordedAt: "2026-09-04",
    },
    closureStatus: "open",
    isSponsored: false,
    professionalDisclaimerShown: false,
    editorialNote: "In the Reseda neighborhood. Tagged in OpenStreetMap as Middle Eastern cuisine, with no street number, phone, or website tagged — this is the thinnest record in this batch and a good early claim candidate. No ownership or halal-certification claim is made or implied by this listing.",
  },
  {
    listingId: "osm-sunnin-lebanese-cafe-westwood",
    name: "Sunnin Lebanese Café",
    slug: "sunnin-lebanese-cafe",
    primaryCategory: "food-drink",
    address: {
      street: "1776 Westwood Boulevard",
      locality: "Los Angeles",
      region: "CA",
      postal: "90024",
    },
    hasPublicStorefront: true,
    countySlug: "los-angeles-county",
    citySlug: "los-angeles",
    telephone: "+1-310-475-3358",
    website: "https://sunnin.com/",
    openingHours: "Mon–Thu, Sun 11:00 am–9:00 pm, Fri–Sat 11:00 am–10:00 pm",
    geo: { lat: 34.0505374, lng: -118.4373991 },

    arabOwnedSelfIdentified: "not_stated",

    claimStatus: "unclaimed",
    verificationLevel: "unverified",
    provenance: {
      source: "OpenStreetMap POI (ODbL)",
      method: "Automated ingestion via Overpass API",
      recordedAt: "2026-09-04",
    },
    closureStatus: "open",
    isSponsored: false,
    professionalDisclaimerShown: false,
    editorialNote: "In Westwood. Tagged in OpenStreetMap as Lebanese cuisine, a long-running LA institution. No ownership or halal-certification claim is made or implied by this listing.",
  },
  {
    listingId: "osm-king-kabob-culver-city",
    name: "King Kabob",
    slug: "king-kabob-culver-city",
    primaryCategory: "food-drink",
    address: {
      street: "Sawtelle Boulevard",
      locality: "Culver City",
      region: "CA",
      postal: "90230",
    },
    hasPublicStorefront: true,
    countySlug: "los-angeles-county",
    citySlug: "culver-city",
    geo: { lat: 33.9949643, lng: -118.3959571 },

    arabOwnedSelfIdentified: "not_stated",

    claimStatus: "unclaimed",
    verificationLevel: "unverified",
    provenance: {
      source: "OpenStreetMap POI (ODbL) + Nominatim reverse geocode for street/postal",
      method: "Automated ingestion via Overpass API",
      recordedAt: "2026-09-04",
    },
    closureStatus: "open",
    isSponsored: false,
    professionalDisclaimerShown: false,
    editorialNote: "In the Sunkist Park neighborhood. Tagged in OpenStreetMap as Middle Eastern cuisine, with no street number, phone, or website tagged. No ownership or halal-certification claim is made or implied by this listing.",
  },
  {
    listingId: "osm-aleppo-kitchen-burbank",
    name: "Aleppo Kitchen",
    slug: "aleppo-kitchen",
    primaryCategory: "food-drink",
    address: {
      street: "2128 Glenoaks Boulevard",
      locality: "Burbank",
      region: "CA",
      postal: "91502",
    },
    hasPublicStorefront: true,
    countySlug: "los-angeles-county",
    citySlug: "burbank",
    telephone: "+1-818-842-2888",
    website: "http://aleppokitchen.com",
    openingHours: "Mon–Wed, Fri–Sat 10:00 am–8:00 pm (closed Thu)",
    geo: { lat: 34.1985240, lng: -118.3265515 },

    arabOwnedSelfIdentified: "not_stated",

    claimStatus: "unclaimed",
    verificationLevel: "unverified",
    provenance: {
      source: "OpenStreetMap POI (ODbL)",
      method: "Automated ingestion via Overpass API",
      recordedAt: "2026-09-04",
    },
    closureStatus: "open",
    isSponsored: false,
    professionalDisclaimerShown: false,
    editorialNote: "Named for Aleppo, Syria. Tagged in OpenStreetMap as Arab cuisine — one of the more explicit cuisine tags in this batch. No ownership or halal-certification claim is made or implied by this listing.",
  },
  {
    listingId: "osm-skafs-grill-north-hollywood",
    name: "Skaf's Grill",
    slug: "skafs-grill",
    primaryCategory: "food-drink",
    address: {
      street: "6008 Laurel Canyon Boulevard",
      locality: "Los Angeles",
      region: "CA",
      postal: "91606",
    },
    hasPublicStorefront: true,
    countySlug: "los-angeles-county",
    citySlug: "los-angeles",
    telephone: "+1-818-551-5540",
    website: "https://skafslebanese.net/",
    openingHours: "Mon–Fri 11:00 am–8:00 pm, Sat 12:00–8:00 pm (closed Sun)",
    geo: { lat: 34.1798120, lng: -118.3960495 },

    arabOwnedSelfIdentified: "not_stated",

    claimStatus: "unclaimed",
    verificationLevel: "unverified",
    provenance: {
      source: "OpenStreetMap POI (ODbL)",
      method: "Automated ingestion via Overpass API",
      recordedAt: "2026-09-04",
    },
    closureStatus: "open",
    isSponsored: false,
    professionalDisclaimerShown: false,
    editorialNote: "In North Hollywood. Tagged in OpenStreetMap as Lebanese cuisine. A second location (SKAF's on York, Eagle Rock) is also listed separately in this directory. No ownership or halal-certification claim is made or implied by this listing.",
  },
  {
    listingId: "osm-adana-restaurant-glendale",
    name: "Adana Restaurant",
    slug: "adana-restaurant",
    primaryCategory: "food-drink",
    address: {
      street: "6918 San Fernando Road",
      locality: "Glendale",
      region: "CA",
      postal: "91201",
    },
    hasPublicStorefront: true,
    countySlug: "los-angeles-county",
    citySlug: "glendale",
    telephone: "+1-818-843-6237",
    website: "https://adanamenu.com/",
    openingHours: "Mon–Sat 11:00 am–8:00 pm, Sun 12:00–8:00 pm",
    geo: { lat: 34.1735960, lng: -118.2984680 },

    arabOwnedSelfIdentified: "not_stated",

    claimStatus: "unclaimed",
    verificationLevel: "unverified",
    provenance: {
      source: "OpenStreetMap POI (ODbL)",
      method: "Automated ingestion via Overpass API",
      recordedAt: "2026-09-04",
    },
    closureStatus: "open",
    isSponsored: false,
    professionalDisclaimerShown: false,
    editorialNote: "Tagged in OpenStreetMap as Middle Eastern cuisine, wheelchair accessible. No ownership or halal-certification claim is made or implied by this listing.",
  },
  {
    listingId: "osm-skafs-on-york-eagle-rock",
    name: "SKAF's on York",
    slug: "skafs-on-york",
    primaryCategory: "food-drink",
    address: {
      street: "4753 York Boulevard",
      locality: "Los Angeles",
      region: "CA",
      postal: "90041",
    },
    hasPublicStorefront: true,
    countySlug: "los-angeles-county",
    citySlug: "los-angeles",
    website: "https://skafsonyork.com/",
    geo: { lat: 34.1225430, lng: -118.2117845 },

    arabOwnedSelfIdentified: "not_stated",

    claimStatus: "unclaimed",
    verificationLevel: "unverified",
    provenance: {
      source: "OpenStreetMap POI (ODbL) + Nominatim reverse geocode for postal code",
      method: "Automated ingestion via Overpass API",
      recordedAt: "2026-09-04",
    },
    closureStatus: "open",
    isSponsored: false,
    professionalDisclaimerShown: false,
    editorialNote: "In Eagle Rock. Tagged in OpenStreetMap as Lebanese cuisine. A second location (Skaf's Grill, North Hollywood) is also listed separately in this directory. No phone number found. No ownership or halal-certification claim is made or implied by this listing.",
  },
];

export function listingsForCounty(countySlug: string): Listing[] {
  return listings.filter((l) => l.countySlug === countySlug);
}
export function listingsForCity(citySlug: string): Listing[] {
  return listings.filter((l) => l.citySlug === citySlug);
}
export function listingsForCategoryInCity(citySlug: string, categorySlug: string): Listing[] {
  return listings.filter(
    (l) =>
      l.citySlug === citySlug &&
      (l.primaryCategory === categorySlug || l.secondaryCategories?.includes(categorySlug))
  );
}
export function getListing(slug: string): Listing | undefined {
  return listings.find((l) => l.slug === slug);
}
